# File: Boilerplate for Drupal 9 Composer.
#
# Description:
# - Creates a brand new Drupal 9 site with development services enabled.
# - Iteration of d9-sandbox project.
# - Installs Composer dependencies from manifest, as most production sites do.

name: d9

# https://docs.lando.dev/config/drupal9.html#getting-started
recipe: drupal9
config:
  webroot: src/web
  composer_version: 2-latest

  # https://docs.lando.dev/config/php.html#supported-versions
  # https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of-drupal-9
  # Drupal 9 requires at least PHP 7.3. PHP 7.4 is also supported but not required. PHP 8 is supported from Drupal 9.1.0.
  # Current official PHP recommendations: https://www.drupal.org/docs/system-requirements/php-requirements

  # For PHP versions available to the Drupal recipe, see
  # https://docs.lando.dev/drupal/
  # https://docs.lando.dev/php/
  php: '8.1'

env_file:
  - lando/default.env
  - lando/private.env

tooling:
  drush:
    description: Executes Drush commands
    service: appserver
    cmd: php /app/src/vendor/bin/drush --root=/app/src

  drupal:
    description: Executes Drupal Console commands
    service: appserver
    cmd: php /app/src/vendor/bin/drupal --root=/app/src

  composer:
    description: Executes composer commands
    service: appserver
    cmd: composer
    dir: /app/src

proxy:
  appserver:
    - d9.lndo.site

services:

  # To see mariadb versions available, see https://docs.lando.dev/mariadb/
  # Version 10.6 is current LTS, supported until July 2026.
  database:
    type: mariadb:10.6
    portforward: false
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
    config:
      database: lando/custom.cnf
    build_as_root:
      - apt update -y
      - apt-get install -y xz-utils zip lz4 pv git

  memcached:
    type: memcached:1
    portforward: false
    mem: 64

  # https://docs.lando.dev/config/php.html#configuration
  appserver:
    app_mount: false
    xdebug: "debug,develop,coverage"
    config:
      php: lando/php.ini

    # https://docs.lando.dev/config/php.html#configuring-xdebug
    overrides:
      tty: true
      # stdin_open: true
      environment:
        DRUSH_OPTIONS_URI: https://d9.lndo.site
        COMPOSER_ALLOW_XDEBUG: 1
        COMPOSER_DISABLE_XDEBUG_WARN: 1
        # https://xdebug.org/docs/all_settings#mode
        # https://docs.lando.dev/php/config.html#configuring-xdebug
        XDEBUG_CONFIG: discover_client_host=false
      volumes:
        # Mount shared source location.
        - ../app:/app
        # Mount custom scripts on top custom mount for lando tooling.
        - lando:/opt/lando
        - container:/opt/container

    build_as_root:
      - addgroup www-data tty

      # Nuke project root if present.
      - echo "Nuking existing project from orbit!"
      - rm -rf /app/src

      # See https://docs.lando.dev/php/extensions.html#adding-or-removing-extensions
      - pecl install uploadprogress
      - docker-php-ext-enable uploadprogress

      # Network debugging tools.
      - apt update -y
      - apt-get install -y telnet iputils-ping iproute2

    # See https://docs.lando.dev/drupal/getting-started.html#quick-start
    build:

      # Clone project source code.
      - git clone git@github.com:AlexanderAllen/example-source-drupal9.git /app/src

      # Install Drupal dependencies via Composer.
      - composer --working-dir=/app/src install

      # Install or import Drupal database.
      - php ${DRUPAL_VENDOR}/bin/drush --root=${COMPOSER_ROOT} site:install -y --db-url=mysql://drupal9:drupal9@database/drupal9 --account-pass=admin --site-name=${LANDO_APP_NAME}

      # Export initial install configuration.
      # - php ${DRUPAL_VENDOR}/bin/drush --working-dir=/app/src @lando cex -y

      # Configure Memcache after database import or Drupal install.
      - php ${DRUPAL_VENDOR}/bin/drush --root=${COMPOSER_ROOT} pm-enable -y memcache
      - cp /opt/container/drupal/sites/memcache.lando.php /app/src/web/sites/default/

      # Smoke test install by running deploy command.
      # - php ${DRUPAL_VENDOR}/bin/drush @lando deploy
