# Boilerplate for Drupal 10.
name: bd9

# https://docs.lando.dev/config/drupal9.html#getting-started
recipe: drupal9
config:
  webroot: .
  composer_version: 2-latest

env_file:
  - lando/default.env
  - lando/private.env

tooling:
  drush:
    description: Executes Drush commands
    service: appserver
    cmd: php /app/vendor/bin/drush --root=/app

  drupal:
    description: Executes Drupal Console commands
    service: appserver
    cmd: php /app/vendor/bin/drupal --root=/app

  composer:
    description: Executes composer commands
    service: appserver
    cmd: composer
    dir: /app

proxy:
  appserver:
    - bd9.lndo.site
  solr:
    - solr.bd9.lndo.site:8983
  pma:
    - pma.bd9.lndo.site

services:

  solr:
    type: solr:8
    portforward: false
    port: 8983
    core: lando
    config:
      dir: config/splits/search_api_solr/jump-start/solr8/config-set

  # https://hub.docker.com/_/phpmyadmin
  # https://docs.phpmyadmin.net/en/latest/setup.html#customizing-configuration
  pma:
    type: compose
    app_mount: false
    portforward: false

    # Generate a certificate for the container on the proxy.
    ssl: true

    services:
      image: phpmyadmin:5.1.1-apache
      command: /docker-entrypoint.sh apache2-foreground
      volumes:
        - ../DatabaseTrustRoot.crt.pem:/opt/DatabaseTrustRoot.crt.pem
        - ./lando/config.user3.inc.php:/etc/phpmyadmin/config.user.inc.php
    build_as_root:
      - apt update
      - apt install -y iputils-ping inetutils-telnet

  database:
    # Nov 13, 2023
    # MariaDB 10.6 is the current long-term maintenance stable version.
    # The first stable release was in July 2021, and it will be maintained until July 2026.
    # https://mariadb.com/kb/en/changes-improvements-in-mariadb-106/
    # https://docs.lando.dev/mariadb/
    type: mariadb:10.6
    portforward: false
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
    config:
      database: lando/custom.cnf
    build_as_root:
      - apt update -y
      - apt-get install -y xz-utils zip lz4 pv git
    overrides:
      volumes:
        - ../DatabaseTrustRoot.crt.pem:/opt/DatabaseTrustRoot.crt.pem

  memcached:
    type: memcached:1
    portforward: false
    mem: 64

  appserver:
    # https://docs.lando.dev/config/php.html#supported-versions
    # https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of-drupal-9
    # Drupal 9 requires at least PHP 7.3. PHP 7.4 is also supported but not required. PHP 8 is supported from Drupal 9.1.0.
    #
    # November 13, 2023
    # Drupal 9.5.11 recommends PHP 8.1.6 or higher, "Drupal wants at least 8.0".
    type: php:8.2

    # https://docs.lando.dev/config/php.html#configuration
    xdebug: "debug,develop,coverage"
    config:
      php: lando/php.ini

    # https://docs.lando.dev/config/php.html#configuring-xdebug
    overrides:
      tty: true
      # stdin_open: true
      environment:
        DRUSH_OPTIONS_URI: https://bd9.lndo.site
        COMPOSER_ALLOW_XDEBUG: 1
        COMPOSER_DISABLE_XDEBUG_WARN: 1
        # https://xdebug.org/docs/all_settings#mode
        XDEBUG_CONFIG: discover_client_host=false

        # Optional, set XDEBUG_MODE manually.
        # XDEBUG_MODE: debug,develop,coverage

        # https://alexanderallen.medium.com/visual-studio-code-wsl-running-php-intellisense-from-alpine-linux-on-windows-10-78e8a990f1cc
        # Set privately via private.env for Windows environments.
        # XDEBUG_CONNECT_BACK: 0
        # XDEBUG_REMOTE_HOST: <replace with WSL ipconfig/eth0>
        # OSX environments may sometimes use:
        # XDEBUG_REMOTE_HOST: host.docker.internal

    build_as_root:
      - addgroup www-data tty

    build:
      - bash -c "echo ''"
